services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: my_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: